#!/usr/bin/env bash
# tapes.sh — regenerate the VHS tapes under docs/tui/tapes/.
#
# What it does: writes one tape per (screen, theme) pair, with the terminal
# colours taken from `engram theme export` rather than typed in.
#
# What it guarantees: no hex value is ever written by hand outside
# internal/tui/theme. A tape carries a literal palette because VHS renders in
# its own terminal emulator and has to be told what the colours are; the only
# way that stays true is for a generator to ask the binary. Edit a palette and
# re-run this, and every tape follows.
#
# Usage:
#   scripts/dev/tapes.sh            # regenerate every tape
#   scripts/dev/tapes.sh --check    # fail if a tape on disk differs
#
# Rendering the tapes is a separate step, because it needs the shots profile:
#   docker compose -f docker-compose.dev.yml --profile shots run --rm vhs tapes/<name>.tape

set -euo pipefail

# shellcheck source=scripts/dev/lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

require_cmd docker jq
assert_no_live_db

TAPE_DIR="$ROOT_DIR/docs/tui/tapes"
CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

# The project every tape opens against. Seeded by scripts/dev/seed.sh.
PROJECT="koi-garden"

# The font the renderer draws with. It has to be a patched monospace face that
# exists inside the VHS image, and both halves of that matter: a proportional
# fallback throws away the cell grid the whole layout is solved against, so the
# capture stops being a picture of the workspace, and an unpatched one draws
# the nerd icon set as blanks. This is the name the image's own fontconfig
# answers to ("JetBrainsMono NFM" is how the Nerd Fonts patcher spells the
# mono variant); `fc-list : family` inside the image lists the rest.
FONT="JetBrainsMono NFM"

# Screens: <name>|<vhs commands, ";" separated>. The digits are the tab bar's
# own bindings: 0 Home, 1 Memory, 2 Tasks, 3 Evidence, 4 Benchmarks,
# 5 Runbooks, 6 Graph, 7 Settings. The overlays are Ctrl+P (project tree),
# Ctrl+K (search palette) and Ctrl+T (theme picker).
SCREENS=(
  'tree|Ctrl+P'
  'home|'
  'memory|Type "1"'
  'tasks|Type "2"'
  'tasks-detail|Type "2";Sleep 1s;Type "j";Sleep 1s;Enter'
  'evidence|Type "3"'
  'benchmarks|Type "4"'
  'runbooks-view|Type "5";Sleep 1s;Type "/";Type "autologin";Enter;Sleep 1s;Enter;Sleep 1s;Type "G"'
  'graph|Type "6"'
  'settings|Type "7"'
  'palette|Ctrl+K;Sleep 1s;Type "lookup"'
  'theme-picker|Ctrl+T'
)

# The dark palette gets every screen; the other three get the three screens
# where the ground colour changes the reading most — the one a reader lands
# on, one dense with badges, and the one that draws its own swatches.
PALETTE_SCREENS=("home" "tasks-detail" "settings")
EXTRA_THEMES=("koi-day" "showa" "ogon")

# vhs_theme turns an exported palette into the JSON object VHS wants.
#
# VHS drives a real terminal emulator, so it asks for the sixteen ANSI slots
# rather than for the workspace's roles. The mapping is the conventional one —
# each role lands on the ANSI colour it stands in for — and it exists so that
# anything the workspace draws with an indexed colour, which is everything
# outside its own styles, still lands inside the theme.
vhs_theme() {
  in_container engram theme export "$1" | jq -Sc '
    .palette as $p |
    {
      background:    $p.base,
      foreground:    $p.text,
      cursor:        $p.primary,
      selection:     $p.surface,
      black:         $p.base,
      red:           $p.danger,
      green:         $p.success,
      yellow:        $p.warning,
      blue:          $p.info,
      magenta:       $p.secondary,
      cyan:          $p.highlight,
      white:         $p.subtext,
      brightBlack:   $p.overlay,
      brightRed:     $p.danger,
      brightGreen:   $p.success,
      brightYellow:  $p.accent,
      brightBlue:    $p.info,
      brightMagenta: $p.secondary,
      brightCyan:    $p.highlight,
      brightWhite:   $p.text
    }'
}

# write_tape renders one tape to stdout.
write_tape() {
  local screen="$1" theme="$2" steps="$3" palette="$4"
  local name="${screen}-${theme}"

  cat <<TAPE
# ${name}: the ${screen} screen in the ${theme} palette.
#
# Generated by scripts/dev/tapes.sh. Do not edit: the Set Theme block below
# is the output of \`engram theme export ${theme}\`, so a hand-written hex
# here would drift from the palette the binary actually resolves.
#
# The window is 1200x900 rather than the 1200x700 a still frame would
# suggest, and the padding is cut to 20px, because the workspace is drawn
# inline rather than into the alternate screen: the shell prompt and the typed
# command stay in the buffer above it and push the frame up, so a window sized
# to the frame loses its tab bar off the top. The extra rows are what keep the
# whole workspace in the picture.
#
# The .gif named by Output is a by-product. VHS records into the file Output
# names and writes a Screenshot out of the recording, so a tape that only
# wants a still frame still has to name a recording — and the Screenshot is
# only written once a later command has advanced the recording past it, which
# is what the trailing Sleep is for.
#
# Render it with the shots profile, from the repository root:
#   docker compose -f docker-compose.dev.yml --profile shots run --rm vhs tapes/${name}.tape

Output "/work/out/${name}.gif"

Set Width 1200
Set Height 900
Set Padding 20
Set FontSize 16
Set FontFamily "${FONT}"
Set Theme ${palette}

Env ENGRAM_DATA_DIR "/data"
Env ENGRAM_VAULT_ROOT "/vault"
Env ENGRAM_TUI_ICONS "nerd"
Env ENGRAM_TIMEZONE "UTC"
Env LANG "C.UTF-8"

Type "engram tui --project ${PROJECT} --theme ${theme}"
Enter
Sleep 3s
TAPE

  if [ -n "$steps" ]; then
    local step
    local IFS=';'
    # shellcheck disable=SC2086
    for step in $steps; do
      [ -n "$step" ] || continue
      printf '%s\n' "$step"
    done
    printf 'Sleep 2s\n'
  fi

  printf '\nScreenshot "/work/out/%s.png"\nSleep 1s\n' "$name"
}

mkdir -p "$TAPE_DIR"

WRITTEN=0
DRIFTED=""

emit() {
  local screen="$1" theme="$2" steps="$3" palette="$4"
  local path="$TAPE_DIR/${screen}-${theme}.tape"
  local rendered
  rendered="$(write_tape "$screen" "$theme" "$steps" "$palette")"

  if [ "$CHECK_ONLY" -eq 1 ]; then
    if [ ! -f "$path" ] || [ "$rendered" != "$(cat "$path")" ]; then
      DRIFTED="$DRIFTED ${screen}-${theme}.tape"
    fi
    return
  fi
  printf '%s\n' "$rendered" >"$path"
  WRITTEN=$((WRITTEN + 1))
}

POND_PALETTE="$(vhs_theme koi-pond)"
for entry in "${SCREENS[@]}"; do
  emit "${entry%%|*}" "koi-pond" "${entry#*|}" "$POND_PALETTE"
done

for theme in "${EXTRA_THEMES[@]}"; do
  palette="$(vhs_theme "$theme")"
  for screen in "${PALETTE_SCREENS[@]}"; do
    for entry in "${SCREENS[@]}"; do
      [ "${entry%%|*}" = "$screen" ] || continue
      emit "$screen" "$theme" "${entry#*|}" "$palette"
    done
  done
done

if [ "$CHECK_ONLY" -eq 1 ]; then
  [ -z "$DRIFTED" ] || fail "these tapes differ from what the palettes produce:$DRIFTED (run scripts/dev/tapes.sh)"
  log "every tape in $TAPE_DIR matches the exported palettes"
  exit 0
fi

log "wrote $WRITTEN tapes to $TAPE_DIR"
